# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxLostArticle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxLostArticle
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'Then'

  pod "SwipeTransition"
  pod "SwipeTransitionAutoSwipeBack"
  pod "SkeletonView"
  pod 'SnapKit', '~> 5.0.0'
  pod 'Hero'

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'ReactorKit'

end
